/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_838666_39.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_838666_4[] = { "Leak", "No_leak" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_838666_38_axes[] = { 0 };
const uint32_t ei_dsp_config_838666_38_axes_size = 1;
ei_dsp_config_spectrogram_t ei_dsp_config_838666_38 = {
    38, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    NULL, // named axes
    0, // size of the named axes array
    0.05f, // float frame_length
    0.05f, // float frame_stride
    128, // int fft_length
    -52, // int noise_floor_db
    true // boolean show_axes
};

const uint8_t ei_dsp_blocks_838666_4_size = 1;
ei_model_dsp_t ei_dsp_blocks_838666_4[ei_dsp_blocks_838666_4_size] = {
    { // DSP block 38
        38,
        6500, // output size
        &extract_spectrogram_features, // DSP function pointer
        (void*)&ei_dsp_config_838666_38, // pointer to config struct
        ei_dsp_config_838666_38_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_838666_38_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_838666_39 = {
    .implementation_version = 1,
    .model = tflite_learn_838666_39,
    .model_size = tflite_learn_838666_39_len,
    .arena_size = tflite_learn_838666_39_arena_size
};

const uint8_t ei_output_tensors_indices_838666_39[1] = { 0 };
const uint8_t ei_output_tensors_size_838666_39 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_838666_39 = {
    .implementation_version = 1,
    .block_id = 39,
    .output_tensors_indices = ei_output_tensors_indices_838666_39,
    .output_tensors_size = ei_output_tensors_size_838666_39,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_838666_39,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_838666_4_size = 1;
const uint32_t ei_learning_block_838666_39_inputs[1] = { 38 };
const uint8_t ei_learning_block_838666_39_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_838666_4[ei_learning_blocks_838666_4_size] = {
    {
        39,
        &run_nn_inference,
        (void*)&ei_learning_block_config_838666_39,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_838666_39_inputs,
        ei_learning_block_838666_39_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_838666_4_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_838666_4[ei_postprocessing_blocks_838666_4_size] = {
    {
        .block_id = 39,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 39
    },
};

const uint8_t freeform_outputs_838666_4_size = 0;

uint32_t *freeform_outputs_838666_4 = nullptr;

const ei_impulse_t impulse_838666_4 = {
    .project_id = 838666,
    .project_owner = "Suporte",
    .project_name = "Sane.AI.Spectrogram v3",
    .impulse_id = 4,
    .impulse_name = "spectrogram",
    .deploy_version = 8,

    .nn_input_frame_size = 6500,
    .raw_sample_count = 240000,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 240000 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 0.020833333333333332,
    .frequency = 48000,

    .dsp_blocks_size = ei_dsp_blocks_838666_4_size,
    .dsp_blocks = ei_dsp_blocks_838666_4,

    .learning_blocks_size = ei_learning_blocks_838666_4_size,
    .learning_blocks = ei_learning_blocks_838666_4,

    .postprocessing_blocks_size = ei_postprocessing_blocks_838666_4_size,
    .postprocessing_blocks = ei_postprocessing_blocks_838666_4,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_MICROPHONE,
    .fusion_string = "audio",
    .slice_size = (240000/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_838666_4,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_838666_4_size,
    .freeform_outputs = freeform_outputs_838666_4
};

ei_impulse_handle_t impulse_handle_838666_4 = ei_impulse_handle_t( &impulse_838666_4 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_838666_4;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_838666_4;
const auto ei_dsp_blocks_size = ei_dsp_blocks_838666_4_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_838666_4;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
